/*
 * Copyright UVSQ - CEA/DAM/DIF (2017-2018)
 * Contributors:  Sebastien GOUGEAUD  -- sebastien.gougeaud@uvsq.fr
 *                Soraya ZERTAL       --      soraya.zertal@uvsq.fr
 *
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
 */

//! \file	decraidvolctrl.hpp
//! \brief	Definition of the declustered RAID controller.

#ifndef _OGSS_DECRAIDVOLCTRL_HPP_
#define _OGSS_DECRAIDVOLCTRL_HPP_

/*----------------------------------------------------------------------------*/
/* HEADERS -------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

#include "controller/volumecontroller.hpp"

#include "scheme/decraidscheme.hpp"

#include "structure/hardware.hpp"

#include "util/unitarytest.hpp"

//! \brief	Controller for a declustered RAID.
class DecRAIDVolCtrl:
public VolumeController {
public:
	friend class UT_DecRAIDVolCtrl;

/*----------------------------------------------------------------------------*/
/* PUBLIC FUNCTIONS ----------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

//! \brief	Constructor.
	DecRAIDVolCtrl (
		const Volume			& vol,
		const Device			& dev,
		const std::vector <Volume>
								& subVols);

//! \brief	Destructor.
	~DecRAIDVolCtrl ();

//! \brief	Request decomposition.
//! \param	request				Request to decompose.
//! \param	subrequests			New requests.
	void decompose (
		Request					& request,
		std::vector <Request>	& subrequests);

//! \brief	Update the volume state when receiving an event.
//! \param	event				Event received.
//! \param	subrequests			Requests created due to the event.
	void updateScheme (
		const Request			& event);

//! \brief	Generate the requests issued from a decraid failure of a given block.
//! \param	block				Block to recover.
//! \param	subrequests			Recovery requests.
	void generateDecraidFailureRequests (
		Request					& block,
		std::vector <Request>	& subrequests);

//! \brief	Generate the requests issued from a decraid renewal of a given block.
//! \param	block				Block to recover.
//! \param	subrequests			Recovery requests.
	void generateDecraidRenewalRequests (
		Request					& block,
		std::vector <Request>	& subrequests);

//! \brief	Generate the requests issued from a failure of a given block.
//! \param	block				Block to recover.
//! \param	subrequests			Recovery requests.
	void generateFailureRequests (
		Request					& block,
		std::vector <Request>	& subrequests);

//! \brief	Generate the requests issued from a renewal of a given block.
//! \param	block				Block to recover.
//! \param	subrequests			Recovery requests.
	void generateRenewalRequests (
		Request					& block,
		std::vector <Request>	& subrequests);

//! \brief	Multiply the requests generated by the volume to take into account
//!			the events.
//! \param	block				Targeted block.
//! \param	subrequests			Requests issued from the multiplier.
	void requestMultiplier (
		Request					& block,
		std::vector <Request>	& subrequests);

//! \brief	Getter of the block location from its logical volume address.
//! \param 	block				Targeted block.
	void getBlockLocation (
		Request					& block);

//! \brief	Getter of the number of data blocks in the requested device.
//! \param	idxDevice			Targeted device index.
//! \return						Requested number of data blocks.
	OGSS_Ulong getNumberDataBlocks (
		OGSS_Ulong				idxDevice);

private:

/*----------------------------------------------------------------------------*/
/* PRIVATE FUNCTIONS ---------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

//! \brief	Update the declustered RAID mapping.
//! \param	vol					Declustered RAID volume.
//! \param	dev					Device contained in the volume.
//! \param	subVols				Subvolumes composing the declustered RAID.
	void updateMapping (
		const Volume			& vol,
		const Device			& dev,
		const std::vector <Volume>	& subVols);

//! \brief	Declustered RAID scheme instanciation.
//! \param	vol 				Declustered RAID volume.
//! \param	dev					Device contained in the volume.
//! \param	subVols				Subvolumes composing the declustered RAID.
	void instanciateScheme (
		const Volume			& vol,
		const std::vector <Volume>	& subVols,
		const Device			& dev);

/*----------------------------------------------------------------------------*/
/* ATTRIBUTES ----------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

	OGSS_Ulong					_numBytesByDev;		//!< Number of bytes by device.
	OGSS_Ulong					_numBytesBySU;		//!< Number of bytes by stripe unit.
	OGSS_Ulong					_numDevices;		//!< Number of devices.
	OGSS_Ulong					_numSpare;			//!< Number of spare devices.
	std::map <OGSS_Ulong, std::unique_ptr <VolumeController>>
								_volCtrls;			//!< Subvolume controllers.
	std::map <OGSS_Ulong, OGSS_Ulong>
								_redirectionTable;	//!< Redirection table (device to subvolume).
	std::unique_ptr <DecRAIDScheme>	_scheme;		//!< Declustered RAID scheme.

	std::map <OGSS_Ulong, OGSS_Real>	_failures;	//!< Failures.
	std::map <OGSS_Ulong, OGSS_Real>	_renewals;	//!< Replacements/renewals.
};

/*----------------------------------------------------------------------------*/
/* UNITARY TEST --------------------------------------------------------------*/
/*----------------------------------------------------------------------------*/

class UT_DecRAIDVolCtrl:
public UnitaryTest <UT_DecRAIDVolCtrl> {
public:
	UT_DecRAIDVolCtrl (
		const OGSS_String		& configurationFile);
	~UT_DecRAIDVolCtrl ();

protected:
	OGSS_Bool manage1Failure ();
	OGSS_Bool manage1Renewal ();
};

#endif
