.TH man 7 "30 Aug 2019" "1.0" "OGMDSim man page"
.SH NAME
OGMDSim \- launch a simulation process of object requests on a metadata storage system
.SH SYNOPSIS
OGMDSim SOURCE
.SH DESCRIPTION
Launch a simulation process using SOURCE as the main configuration file, which contains information about the requests, the storage system and the application parameters.
.SH COMPILATION AND MAIN UTILISATION
To compile OGMDSim, use the provided makefile. The modes debug and release are both available.
.PP
There exists two utilisation modes for OGMDSim. You can use it as a standalone if you only want to get the metrics of a given metadata system or you can call it inside OGSSim (by providing the right information in OGSSim configuration file) if you want to get the metrics of the whole data storage system or if you only get objet requests and you need to translate them into logical block requests. In both cases, the configuration file of OGMDSim must be provided.
.SH CONFIGURATION FILE
The configuration file of OGMDSim consists of an XML file which contains the following tags:
.RS
.TP 20
.B <config>
Main tag.
.PD 0
.RS 2
.TP 18
.B <global>
Global behavior of the application.
.RS 2
.TP 16
.B <chrono>
Activate the chronometer on the metadata system construction.
.RE
.TP
.B <path>
File paths used during the process.
.RS 2
.TP 16
.B <system>
System file path.
.TP
.B <trace>
Trace file path.
.TP
.B <output>
Output file path.
.RE
.TP
.B <score>
Score definition for the metadata system shortest path generation. The attribute
.B defbounds
can be set to false to indicate that the bounds need to be determined thanks to the min and max value, during the score computation.
.RS 2
.TP 16
.B <latency>
Latency bounds for the score computation by setting the attributes
.B min
and
.B max.
.TP
.B <nbjumps>
Bounds of the number of jumps for the score computation by setting the attributes
.B min
and
.B max.
.TP
.B <rate>
Latency rate in the score computation.
.RE
.TP
.B <distribution>
Rules used to generate the object metadata information.
.RS 2
.TP 16
.B <datafactor>
Factor used as a unit for all data values.
.TP
.B <address>
Generation strategy used for the data address field, chosen between
.B sequential
and
.B uniform.
The
.B max
attribute is used to define the size of the logical data space. The
.B min
attribute can be used with the
.B uniform
random strategy to define a minimum obtainable address.
.TP
.B <size>
Generation strategy used for the data size field, chosen between
.B constant
and
.B uniform.
The
.B constant
strategy is parametrized using the
.B value
attribute. The
.B uniform
strategy is parametrized using the
.B min
and
.B max
attributes.
.RE
.RE
.PD
.SH SYSTEM FILE
The system file consists of an XML file which contains the following tags:
.RS
.TP 20
.B <system>
Main tag.
.PD 0
.RS 2
.TP 18
.B <global>
Global parameters of the metadata system.
.RS 2
.TP 16
.B <nbhost>
Number of host servers.
.TP
.B <nbmetadata>
Number of metadata servers.
.TP
.B <loadbalancing>
Soft limit for the server filling policy. If a server load reaches this limit, the other servers will be filled before continuing to fill the first one.
.TP
.B <mssize>
Metadata server size. If the
.B unit
attribute can be set to
.B object
or
.B byte.
If the
.B byte
attribute is chosen, the tag
.B <mosize> must be provided.
.TP
.B <mosize>
Metadata object size in bytes.
.RE
.TP
.B <maintenance>
Parameters of the maintenance routine.
.RS 2
.TP 16
.B <model>
Maintenance model, chosen between
.B threshold, average
and
.B no
(if no maintenance routine).
The threshold model is parametrized using the
.B <softlim>
and
.B <hardlim>
tags.
.TP
.B <period>
Elapsed time (s) between two maintenance routines.
.TP
.B <histsize>
Server load history size.
.TP
.B <oblivrate>
Oblivion rate ie. rate of the history average load against the current server load. Used by the
.B average
model.
.TP
.B <output>
Output file for the server load evolution. If the tag is not provided, none output is generated.
.TP
.B <softlim>
Soft limit for the
.B threshold
model. Used as a value to reach when reducing the server load.
.TP
.B <hardlim>
Hard limit for the
.B threshold
model. Used to launch the maintenance routine.
.RE
.TP
.B <path>
File paths used by the system extraction process.
.RS 2
.TP 16
.B <matrix>
Matrix file path.
.RE
.RE
.RE
.PD
.SH MATRIX FILE
The matrix file consists of a RAW file which contains the latencies between all the servers of the metadata system. The latency represents the average transfer time (s) for a metadata block. The number of lines and columns are equals to the number of servers, number provided in the system file. A latency equals to -1 means that the servers are not directly linked.
.SH TRACE FILE
The trace file consists of a raw file which contains the requests that will be processed by OGMDSim. Each request/line is composed of 4 fields: the arrival date (s), the data access type (0 for read access, 1 for write), the host server which sends the requests and the object ID.
.SH OUTPUT FILE
The output file generated by OGMDSim consists of a RAW file which contains the data requests issued from the metadata request processing. Each request is described by its arrival date, its access type, its logical address and its size. This file can be directly read by OGSSim. 
.SH AUTHORS
Sebastien Gougeaud (sebastien.gougeaud@uvsq.fr)
.br
Soraya Zertal (soraya.zertal@uvsq.fr)
